version: "3.2"
services:
  app:
    command: node src/app.js
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-5000}
        target: 5000
    volumes:
      - .:/app/
    environment:
      JWT_SECRET: ${JWT_SECRET}
