version: "3.2"
services:
  mongo:
    image: "mongo:latest"
        
  api:
    build:
      context: ./MovieAPI
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-5000}
        target: 5000
    environment:
      JWT_SECRET: ${JWT_SECRET}
      MONGO_URL: 'mongodb://mongo:27017/db'
    depends_on:
      - mongo
