# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create mongoDB Docker container for API testing
      uses: DigiPie/mongo-action@v1.0.1
    - name: Install npm packages for Auth
      run: npm install
      working-directory: ./Auth
    - name: run Auth service
      run: node ./src/server.js &
      working-directory: ./Auth
      env:
        JWT_SECRET: secret
    - name: Install npm packages for Movie API
      run: npm ci
      working-directory: ./MovieAPI
    - name: Run `npm test` for MovieAPI
      run: npm test
      working-directory: ./MovieAPI
      env:
        JWT_SECRET: secret
        AUTH_URL: http://localhost:3000/auth
        TEST_MONGO_URL: mongodb://localhost:27017/db_test # Access mongoDB Docker container
